name: Poll Order Book & Push to Google Drive

# Run every 5 minutes (GitHub Actions’ minimum)
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  poll_and_upload:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Install rclone
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      # 5) Write the service-account JSON into /tmp/sa.json
      - name: Write service-account key to /tmp/sa.json
        run: |
          mkdir -p /tmp
          # The SA_JSON secret must contain only raw service-account JSON.
          echo "${{ secrets.SA_JSON }}" > /tmp/sa.json
        shell: bash

      # 6) Generate ~/.config/rclone/rclone.conf with no leading spaces
      - name: Generate rclone.conf
        run: |
          mkdir -p ~/.config/rclone/
          cat <<EOF > ~/.config/rclone/rclone.conf
          [mygdrive]
          type = drive
          scope = drive.file
          service_account_file = /tmp/sa.json
          root_folder_id = 1ho3ut4U-8W7lxQm8E8nRgOQFi0GHpok2
          EOF
        shell: bash

      # 7) Run your Python polling script
      - name: Poll order-book and append to CSV
        run: |
          python eth_poll_orderbook.py

      # 8) Upload the updated CSV to Google Drive
      - name: Upload CSV to Google Drive
        run: |
          rclone copy orderbook_snapshots.csv mygdrive:
