name: Poll Order Book & Push to Google Drive (every 5 minutes)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  poll_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            ccxt \
            google-api-python-client \
            google-auth-httplib2 \
            google-auth-oauthlib

      - name: Set up credentials.json
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS_JSON }}" > credentials.json

      - name: Restore token.pickle (optional)
        env:
          GDRIVE_TOKEN_PICKLE_BASE64: ${{ secrets.GDRIVE_TOKEN_PICKLE_BASE64 }}
        run: |
          if [ -n "$GDRIVE_TOKEN_PICKLE_BASE64" ]; then
            echo "$GDRIVE_TOKEN_PICKLE_BASE64" | base64 -d > token.pickle
          else
            echo "No token.pickle secret provided; skipping restore"
          fi

      - name: Poll orderbook and sync with Google Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python poll_and_sync.py
