# .github/workflows/poll.yml

name: Poll Order Book & Push to Google Drive

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes

jobs:
  poll_and_upload:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install Python dependencies (ccxt)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Install rclone (so we can push to Drive)
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      # 5) Write the rclone.conf from the RCLONE_CONFIG secret
      - name: Configure rclone with Service Account
        run: |
          mkdir -p ~/.config/rclone/
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf
        shell: bash

      # 6) Poll the order book and append a row to the CSV
      - name: Poll order-book and append to CSV
        run: |
          python eth_poll_orderbook.py

      # 7) Upload the updated CSV to Google Drive via rclone
      - name: Upload CSV to Google Drive
        run: |
          rclone copy orderbook_snapshots.csv mygdrive:
