name: Poll Order Book & Push to Google Drive (every 5 minutes)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  poll_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            ccxt \
            google-api-python-client \
            google-auth-httplib2 \
            google-auth-oauthlib

      - name: Write GCP service account key
        env:
          SA_KEY: ${{ secrets.GDRIVE_SA_KEEE }}
        run: |
          echo "$SA_KEY" > ${{ runner.temp }}/sa_key.json

      - name: Poll orderbook and sync with Google Drive
        env:
          # Tell the client library where to find the key
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/sa_key.json
          # Your Drive folder ID secret
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python poll_and_sync.py
