name: Poll Order Book & Push to Google Drive (via Python API)

on:
  schedule:
    - cron: "*/5 * * * *"     # every 5 minutes

jobs:
  poll_and_upload:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install Python dependencies (ccxt + Google Drive libs)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt google-api-python-client google-auth

      # 4) Poll the order-book and append to CSV
      - name: Poll order-book and append to CSV
        run: |
          python eth_poll_orderbook.py

      # 5) Upload CSV to Google Drive via Python API
      - name: Upload CSV to Google Drive
        env:
          GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}
          GDRIVE_FOLDER_ID: "1ho3ut4U-8W7lxQm8E8nRgOQFi0GHpok2"   # or store this in a secret, too
        run: |
          python upload_drive.py
