# .github/workflows/poll.yml

name: Poll Order Book & Push to Google Drive (every 5 minutes)

on:
  schedule:
    - cron: "*/5 * * * *"    # every 5 minutes UTC
  workflow_dispatch:        # allow manual run

jobs:
  poll_and_upload:
    runs-on: ubuntu-latest
    concurrency:
      group: poll-and-upload       # or any unique name
      cancel-in-progress: false     # do NOT wait for the previous run; simply drop the new one
    steps:
      # 1) Check out the repository (we need the code files)
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Set up Python (we need ccxt & Google Drive libraries)
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3) Install our Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt google-api-python-client google-auth

      # 4) Run the unified polling + Drive sync script
      - name: Poll orderbook and sync with Google Drive
        env:
          GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python poll_and_sync.py
