# .github/workflows/poll.yml

name: Poll Order Book & Push to Google Drive (every 5 minutes)

on:
  schedule:
    - cron: "*/5 * * * *"    # every 5 minutes UTC
  workflow_dispatch:        # allow manual runs

jobs:
  poll_and_upload:
    runs-on: ubuntu-latest
    concurrency:
      group: poll-and-upload
      cancel-in-progress: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            ccxt \
            google-api-python-client \
            google-auth-httplib2 \
            google-auth-oauthlib

      # ─────────────────────────────────────────────────────────────────────
      # Provide OAuth client credentials
      # ─────────────────────────────────────────────────────────────────────

      # Option 1: credentials.json committed privately in repo
      # (Skip these two steps if credentials.json is already in your repo root.)

      - name: Set up credentials.json
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS_JSON }}" > credentials.json

      - name: Restore token.pickle (optional on first run)
        if: ${{ secrets.GDRIVE_TOKEN_PICKLE_BASE64 }}
        run: |
          echo "${{ secrets.GDRIVE_TOKEN_PICKLE_BASE64 }}" \
            | base64 -d > token.pickle

      # ─────────────────────────────────────────────────────────────────────
      # Run the script
      # ─────────────────────────────────────────────────────────────────────

      - name: Poll orderbook and sync with Google Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python poll_and_sync.py
