 name: Poll Order Book & Push to Google Drive (every 5 minutes)

 on:
   schedule:
     - cron: '*/5 * * * *'
   workflow_dispatch:

 jobs:
   poll_and_upload:
     runs-on: ubuntu-24.04

     steps:
       - name: Check out repository
         uses: actions/checkout@v4

       - name: Cache pip
         uses: actions/cache@v3
         with:
           path: ~/.cache/pip
           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
           restore-keys: ${{ runner.os }}-pip-

       - name: Download previous token.pickle (if any)
         uses: actions/download-artifact@v4
         with:
           name: token-pickle
           path: .
         continue-on-error: true

       - name: Set up Python 3.9
         uses: actions/setup-python@v4
         with:
           python-version: '3.9'

       - name: Restore GCP service account key
         run: |

          printf '%s' "${{ secrets.GCP_SA_KEY2 }}" > sa-key.json

       - name: Install Python dependencies
         run: |
           python -m pip install --upgrade pip
           pip install ccxt google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Poll orderbook and sync with Google Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          # point at the file you just wrote
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa-key.json
        run: python poll_and_sync.py

       - name: Upload updated token.pickle
         if: success()
         uses: actions/upload-artifact@v4
         with:
           name: token-pickle
           path: token.pickle
